name: Nuclear
main: me.matchers.spark.SparkPlugin
version: 1.1-SNAPSHOT
author: Matchers



#Changelog:

#1.1:
# Added freezing & filter
# Added random util
# Added config reload
# Added spark command (displays plugin ver)

